name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - uses: coursier/cache-action@v6
      - name: Validate project    
        run: sbt validate
